### ISSUE TITLE
Triple single-quotes does not generate docstring (MacOS)

### ISSUE THREAD

**Issue by slw07g** [NilsJPWerner/autoDocstring#135] opened 2020-05-13 15:28 UTC
**Describe the bug**
Triple single-quotes (followed by enter) does not generate docstring, but triple double-quotes does. 

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.1
- Operating System: OS X Catalina 10.15.5 Beta
- Vscode Version: 1.45.0

**Original Code (with line to generate on):**
```
def get_member(self):
> docstring here <
        return self._member
```

**Expected Result:**
```
def get_member(self):
        '''[summary]

        Returns:
            [type] -- [description]
        '''
        return self._member
```

**Actual Result:**
```
def get_member(self):
        '''
        return self._member
```

**Additional context**
N/A

**Comment by NilsJPWerner** [comment] 2020-05-17 21:28
Duplicate of #125 
Fixed in #132

**Closed by NilsJPWerner** 2020-05-17 21:28 UTC
Labels: bug
