### ISSUE TITLE
Extra whitespaces added after the end of the docstring closing.

### ISSUE THREAD

**Issue by sometowngeek** [NilsJPWerner/autoDocstring#208] opened 2021-12-13 16:09 UTC
**Describe the bug**
the autoDocString keeps on adding extra spaces to after the end of the docstring which causes some linters like Sonar to create issues. It becomes bothersome to keep having to erase the extra ~4 spaces every time we create a docstring with this extension. It would be nice to see no additional, unnecessary spaces added.

**Versions (please complete the following information):**
- autoDocstring Version: v0.5.4
- Operating System: Windows 10
- Vscode Version: 1.63.0

**Original Code (with line to generate on):**
```python
# generate on this line
def foo(message:str) -> None:
    print(f"MESSAGE: {message}")
```

**Expected Result:**
```pythondef foo(message:str) -> None:
    """
    [summary]

    Args:
        message (str): [description]
    """# autoDocString does not add any extra spacing at the end of closing triple quotes.
    print(f"MESSAGE: {message}")
```

**Actual Result:**
```pythondef foo(message:str) -> None:
    """
    [summary]

    Args:
        message (str): [description]
    """    # autoDocString added extra spacings at the end of closing triple quotes.
    print(f"MESSAGE: {message}")
```

**Stack trace:**
If an error was reported by autodocstring please copy the stack trace from the `autoDocstring` output channel.

There was no error message, but I thought the stack trace might be useful anyway.
```
[INFO 07:29:43.780] autoDocstring was activated
[INFO 09:43:52.845] Generating Docstring at line: 1771
[INFO 09:43:52.904] Docstring generated:
        """${1:[summary]}

        Args:
            benefit_prefix (${2:[type]}): ${3:[description]}

        Raises:
            AttributeError: ${4:[description]}

        Returns:
            ${5:[type]}: ${6:[description]}
        """
[INFO 09:43:52.904] Inserting at position: 1771 0
[INFO 09:43:52.967] Successfully inserted docstring
[INFO 10:01:36.192] Generating Docstring at line: 1
[INFO 10:01:36.202] Docstring generated:
    """
    ${1:[summary]}

    Args:
        message (${2:str}): ${3:[description]}
    """
[INFO 10:01:36.202] Inserting at position: 1 0
[INFO 10:01:36.224] Successfully inserted docstring
```

**Additional context**
This causes some linters like SonarQube to create issues for unused whitespaces. It would be nice if the autoDocString would avoid creating extra spaces or at least clear up the end of the closing of docstring.

**Comment by NilsJPWerner** [comment] 2022-02-13 00:13
Duplicate of #162

**Closed by NilsJPWerner** 2022-02-13 00:13 UTC
Labels: bug
