### ISSUE TITLE
Docstring not getting generated when method already has a triple-quoted string

### ISSUE THREAD

**Issue by jintolonappan** [NilsJPWerner/autoDocstring#142] opened 2020-06-04 23:07 UTC
**Describe the bug**
Extension is not getting prompted to generate docstring after adding triple quoted string (Either single quote or double quote) when there already is a triple quoted string at any part of the method. 

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.3 - 2020-06-03
- Operating System: MacOS Mojave 10.14.6
- Vscode Version: February 2020 - 1.43.2

**Actual Result:**
```python
def triple_str_docstrextn():
    """[This works]
    """
    pass

def nogo_triple_str_docstrextn():
    """ <Not working - No prompt to generate docstring>
    <Result is the same if we use " or ' >

    long_var = """
    1
    2
    3
    4"""
    pass
```

**Stack trace:**
If an error was reported by autodocstring please copy the stack trace from the `autoDocstring` output channel.
```
Docstring is not producing any log in this case.
```

**Additional context**

**Comment by NilsJPWerner** [comment] 2020-06-30 14:09
Duplicate of: https://github.com/NilsJPWerner/autoDocstring/issues/68 

I will work on a fix this weekend.

**Closed by NilsJPWerner** 2020-06-30 14:09 UTC
Labels: bug
