### ISSUE TITLE
autoDocstring should ignore inline comments when generating a docstring

### ISSUE THREAD

**Issue by hellocoldworld** [NilsJPWerner/autoDocstring#173] opened 2020-12-22 14:50 UTC
**Describe the bug**
The docstring wrongly assumes a parameter is optional and witha default value when the line of the arguments ends with a comment.

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.3
- Operating System: Ubuntu 18.04.4 LTS (MATE desktop)
- Vscode Version:  1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523) x64 ([vscodium](https://vscodium.com/) binaries)

**Original Code (with line to generate on):**
```python
def foo(
    a: int, b: float # pylint: # pylint: disable=unused-argument
) -> None:
```

**Expected Result:**
```python
    """[summary]

    Args:
        a (int): [description]
        b (float): [description]
    """
```

**Actual Result:**
```python
    """[summary]

    Args:
        a (int): [description]
        b (float, optional): [description]. Defaults to unused-argument.
    """
```

** Output of autoDocstring **
```bash
[INFO 11:49:00.771] Generating Docstring at line: 5
[INFO 11:49:00.772] Docstring generated:
    """${1:[summary]}

    Args:
        a (${2:int}): ${3:[description]}
        b (${4:float}, optional): ${5:[description]}. Defaults to unused-argument.
    """
[INFO 11:49:00.772] Inserting at position: 5 0
[INFO 11:49:00.780] Successfully inserted docstring
```

**Comment by NilsJPWerner** [comment] 2021-03-08 05:03
Duplicate of https://github.com/NilsJPWerner/autoDocstring/issues/160

**Closed by NilsJPWerner** 2021-03-08 05:03 UTC
Labels: bug
