### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by vmasrani** [NilsJPWerner/autoDocstring#107] opened 2020-03-30 19:26 UTC
- Issue Type: `Bug`
- Extension Name: `autodocstring`
- Extension Version: `0.4.0`
- OS Version: `Darwin x64 19.3.0`
- VSCode version: `1.43.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 28,
		"activateCallTime": 0,
		"activateResolvedTime": 21,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "njpwerner.autodocstring",
				"_lower": "njpwerner.autodocstring"
			},
			"activationEvent": "onLanguage:python"
		}
	},
	"runtimeErrors": [
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		},
		{
			"name": "Error",
			"message": "Illegal argument: character must be non-negative"
		}
	]
}
```

**Comment by NilsJPWerner** [comment] 2020-04-05 04:45
@vmasrani Can you post the piece of code you used autodocstring on that caused this issue?

**Comment by NilsJPWerner** [comment] 2020-05-18 14:24
I think this is a duplicate of #101

**Closed by NilsJPWerner** 2020-05-18 14:24 UTC
Labels: need more info
