### ISSUE TITLE
Extra spaces after closing quotations

### ISSUE THREAD

**Issue by fehtemam** [NilsJPWerner/autoDocstring#176] opened 2021-02-23 21:13 UTC
**Describe the bug**
Auto insert always leaves extra spaces after the closing quotations:

```python
def my_fun(x1, x2):
        """Do something.
        """            <---- Here
```

These extra spaces violate flake8 linting rules and have to be removed manually. Is there a way to change the settings to avoid these extra spaces?

**Versions (please complete the following information):**
- autoDocstring Version: 0.5.4
- Operating System: MacOS
- Vscode Version: 1.53.2

**Comment by NilsJPWerner** [comment] 2021-03-08 04:45
I can't recreate this issue. What is your docstring format?

**Comment by NilsJPWerner** [comment] 2021-03-08 04:52
Duplicate of https://github.com/NilsJPWerner/autoDocstring/issues/162

**Closed by NilsJPWerner** 2021-03-08 04:52 UTC
Labels: bug
